#!perl

# this script requires JFR::Fasta
# https://github.com/josephryan/JFR-PerlModules
# removes sequences from a FASTA file that have only gap characters (-)

# Copyright (C) 2017,2018; Joseph F. Ryan <joseph.ryan@whitney.ufl.edu>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# for more info see <http://www.gnu.org/licenses/>

our $VERSION = 0.01;

use strict;
use warnings;
use JFR::Fasta;

MAIN: {
    my $fa = $ARGV[0] or die "usage: $0 FASTA\n";
    my $fp = JFR::Fasta->new($fa);
    open OUT, ">$fa.res" or die "cannot open >$fa.res:$!";
    while (my $rec = $fp->get_record()) {
        $rec->{'seq'} =~ s/ //g;
        next if ($rec->{'seq'} =~ m/^\-+$/);
        print OUT "$rec->{'def'}\n$rec->{'seq'}\n";
    }
}
